In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)


df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])


columns_to_drop = [
    # PII / no analytical value
    'Customer Email',
    'Customer Password',
    'Customer Fname',
    'Customer Lname',
    'Customer Street',

    # Empty or near-useless
    'Product Description',      # 100% missing
    'Product Image',            # just a URL
    'Order Zipcode',            # ~86% missing
    'Product Status',            # ~99% missing
    # Redundant duplicate IDs
    'Order Customer Id',        # duplicate of Customer Id
    'Product Category Id',      # duplicate of Category Id
    'Order Item Cardprod Id',   # duplicate of Product Card Id
]
df_clean = df.drop(columns=columns_to_drop)

df_clean = df_clean.rename(columns={'shipping date (DateOrders)': 'Shipping_Date', 
                                    'order date (DateOrders)': 'Order_Date',
                                    'Days for shipping (real)' : 'Shipping_days',
                                    'Days for shipment (scheduled)' : 'Scheduled_shipping_days', 
                                    'Order Profit Per Order' : 'Profit_per_order',
                                      'Order Item Discount Rate' : 'Discount_rate', 
                                      'Order Item Profit Ratio' : 'Profit_ratio',
                                      'Order Item Quantity' : 'Quantity',
                                      'Order Item Product Price' : 'Prroduct_price',
                                      'Order Item Discount' : 'Discount',
                                      'Order Item Total' : 'Order_item_total',
                                      'Shipping Mode' : 'Shipping_mode',
                                      'Order Region' : 'Order_region',
                                      'Order State': 'Order_state',
                                      'Order Status' : 'Order_status'})   #Renaming columns

df_clean = df_clean.fillna({'Customer Zipcode': '00000'})   #Replacing values in customer zipcode with '00000'

In [2]:
sales_profit = df_clean.groupby('Category Name').agg(
    Total_sales=('Sales', 'sum'),
    Total_profit=('Profit_per_order', 'sum')
).round(2).reset_index()

sales_profit = sales_profit.sort_values(by='Total_sales', ascending=False).reset_index(drop=True)

In [3]:
sales_profit.head(10)

          Category Name  Total_sales  Total_profit
0               Fishing   6929653.69     756220.77
1                Cleats   4431942.78     494636.92
2      Camping & Hiking   4118425.57     427455.57
3      Cardio Equipment   3694843.20     383011.10
4       Women's Apparel   3147800.00     350421.03
5          Water Sports   3113844.68     325146.96
6        Men's Footwear   2891757.66     311902.82
7  Indoor/Outdoor Games   2888993.91     318451.43
8         Shop By Sport   1309522.04     129813.96
9             Computers    663000.00      69656.81

In [4]:
sales_profit_segment = df_clean.groupby('Customer Segment').agg(
    Total_sales=('Sales', 'sum'),
    Total_profit=('Profit_per_order', 'sum')
).round(2).reset_index()

sales_profit_segment = sales_profit_segment.sort_values(by='Total_sales', ascending=False).reset_index(drop=True)

sales_profit_segment

  Customer Segment  Total_sales  Total_profit
0         Consumer  19095790.16    2073487.67
1        Corporate  11168406.84    1202574.96
2      Home Office   6520538.02     690840.34

In [5]:
sales_profit_market = df_clean.groupby('Market').agg(
    Total_sales=('Sales', 'sum'),
    Total_profit=('Profit_per_order', 'sum')
).round(2).reset_index()

sales_profit_market = sales_profit_market.sort_values(by='Total_sales', ascending=False).reset_index(drop=True)

sales_profit_market

         Market  Total_sales  Total_profit
0        Europe  10872396.80    1169442.96
1         LATAM  10277612.84    1123321.61
2  Pacific Asia   8273743.74     857753.44
3          USCA   5066528.71     564313.78
4        Africa   2294452.93     252071.18