In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)


df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])


columns_to_drop = [
    # PII / no analytical value
    'Customer Email',
    'Customer Password',
    'Customer Fname',
    'Customer Lname',
    'Customer Street',

    # Empty or near-useless
    'Product Description',      # 100% missing
    'Product Image',            # just a URL
    'Order Zipcode',            # ~86% missing
    'Product Status',            # ~99% missing
    # Redundant duplicate IDs
    'Order Customer Id',        # duplicate of Customer Id
    'Product Category Id',      # duplicate of Category Id
    'Order Item Cardprod Id',   # duplicate of Product Card Id
]
df_clean = df.drop(columns=columns_to_drop)

df_clean = df_clean.rename(columns={'shipping date (DateOrders)': 'Shipping_Date', 
                                    'order date (DateOrders)': 'Order_Date',
                                    'Days for shipping (real)' : 'Shipping_days',
                                    'Days for shipment (scheduled)' : 'Scheduled_shipping_days', 
                                    'Order Profit Per Order' : 'Profit_per_order',
                                      'Order Item Discount Rate' : 'Discount_rate', 
                                      'Order Item Profit Ratio' : 'Profit_ratio',
                                      'Order Item Quantity' : 'Quantity',
                                      'Order Item Product Price' : 'Prroduct_price',
                                      'Order Item Discount' : 'Discount',
                                      'Order Item Total' : 'Order_item_total',
                                      'Shipping Mode' : 'Shipping_mode',
                                      'Order Region' : 'Order_region',
                                      'Order State': 'Order_state',
                                      'Order Status' : 'Order_status'})   #Renaming columns

df_clean = df_clean.fillna({'Customer Zipcode': '00000'})   #Replacing values in customer zipcode with '00000'

In [2]:
Country_summary = (
    df_clean
    .groupby('Order Country')
    .agg(
        Order_count=('Order Id', 'nunique'),
        Total_sales=('Sales', 'sum'),
        Total_profit=('Profit_per_order', 'sum')
    )
    .round(2)
    .reset_index()
)
Country_summary = Country_summary.sort_values(by='Order_count', ascending=False).reset_index(drop=True)
Country_summary.head(10)

    Order Country  Order_count  Total_sales  Total_profit
0  Estados Unidos         8270   4879667.67     540413.07
1         Francia         4866   2879942.36     327828.58
2          México         4395   2633195.29     303278.37
3       Australia         3798   1694621.67     170041.58
4        Alemania         3518   2074171.82     194827.08
5     Reino Unido         2785   1612094.85     180942.88
6          Brasil         2650   1594319.95     186713.64
7           China         2616   1172902.11     122190.92
8           India         2152    962396.70      99746.82
9       Indonesia         1920    847605.93      90714.08

In [3]:
Region_summary = (
    df_clean
    .groupby('Order_region')
    .agg(
        Order_count=('Order Id', 'nunique'),
        Total_sales=('Sales', 'sum'),
        Total_profit=('Profit_per_order', 'sum')
    )
    .round(2)
    .reset_index()
)
Region_summary = Region_summary.sort_values(by='Order_count', ascending=False).reset_index(drop=True)
Region_summary.head(5)

      Order_region  Order_count  Total_sales  Total_profit
0   Western Europe        10010   5894380.77     625446.08
1  Central America         9396   5665712.10     616341.57
2    South America         4979   2960881.41     335154.40
3          Oceania         4362   2016654.20     201478.02
4   Southeast Asia         4356   1932495.57     211342.82